name: Java CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    # Add environment variables for secrets
    env:
      CALCULATOR_API_KEY: ${{ secrets.CALCULATOR_API_KEY }}
      VALIDATION_ENDPOINT: ${{ secrets.VALIDATION_ENDPOINT }}
   
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'

    - name: Verify Java version
      run: java -version
 
    - name: Verify Maven Java version
      run: mvn -version
 
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    # Add step to verify secrets are available (optional, for debugging)
    - name: Verify Secrets
      run: |
        if [ -n "$CALCULATOR_API_KEY" ]; then
          echo "API key is set"
        else
          echo "API key is not set"
        fi
        if [ -n "$VALIDATION_ENDPOINT" ]; then
          echo "Validation endpoint is set"
        else
          echo "Validation endpoint is not set"
        fi

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test

    - name: Generate test report
      run: mvn surefire-report:report
     
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: target/surefire-reports