name: Java CI/CD Pipeline

# Defines when the workflow runs
on:
  push:
    branches: [ main ]  # Runs on pushes to main branch
  pull_request:
    branches: [ main ]  # Runs on PRs targeting main branch
  workflow_dispatch:    # Allows manual trigger from GitHub UI

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Java environment
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'

    # Step 2.5: Verify Java version
    - name: Verify Java version
      run: java -version
  
    # Step 2.6: Check Maven Java version
    - name: Verify Maven Java version
      run: mvn -version
  

    # Step 3: Cache Maven packages
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    # Step 4: Build the project
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Step 5: Run tests
    - name: Run tests
      run: mvn test

    # Step 6: Generate test report
    - name: Generate test report
      run: mvn surefire-report:report
      
    # Step 7: Upload test results
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: target/surefire-reports
