# .github/workflows/security.yml
name: Security Checks

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Daily scan

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'Calculator'
          path: '.'
          format: 'HTML'

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'calculator:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload security results
        uses: actions/upload-artifact@v4
        with:
          name: Security-Reports
          path: |
            dependency-check-report.html
            trivy-results.txt