name: Security Checks

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # Add this step to explicitly set JAVA_HOME
      - name: Set JAVA_HOME
        run: |
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      # Alternative approach using Maven plugin instead of Action
      - name: Run OWASP Dependency Check
        run: |
          mvn org.owasp:dependency-check-maven:check

      - name: Build Docker image
        run: docker build -t calculator:latest -f terraform/Dockerfile .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'calculator:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload security results
        uses: actions/upload-artifact@v4
        with:
          name: Security-Reports
          path: |
            target/dependency-check-report.html
            trivy-results.txt