# .github/workflows/security.yml
name: Security Checks

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Add Java setup BEFORE dependency check
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'Calculator'
          path: '.'
          format: 'HTML'

      # Build Docker image before Trivy scan
      - name: Build Docker image
        run: docker build -t calculator:latest -f terraform/Dockerfile .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'calculator:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      - name: Upload security results
        uses: actions/upload-artifact@v4
        with:
          name: Security-Reports
          path: |
            dependency-check-report.html
            trivy-results.txt